services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: booking-backend-dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend/src:/app/src
      - ./backend/package.json:/app/package.json
      - ./backend/tsconfig.json:/app/tsconfig.json
      - booking_db:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_PATH=/app/data/bookings.db
    networks:
      - booking-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: booking-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
    environment:
      - VITE_API_BASE_URL=http://localhost:3001/api
      - VITE_ENV=development
    networks:
      - booking-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    stdin_open: true
    tty: true

networks:
  booking-network:
    driver: bridge
    name: booking-dev-network

volumes:
  booking_db:
    name: booking-dev-db
